name: Deploy Container
on:
  push:
    branches: [ main ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    outputs:
      instance_public_url: ${{steps.deploy.outputs.vm_url}}
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-2

          ansible_start_docker_timeout: 60000

          aws_elb_app_port: 80,81 # This should match the docker exposed port. Defaults to 3000.
  Get-Instance-Info:
    runs-on: ubuntu-latest
    needs: EC2-Deploy
    outputs:
      instance_public_ip: ${{steps.get-address.outputs.ip_address}}
    steps:
      - id: checkout-repository
        uses: actions/checkout@v2

      - id: get-address
        run: |
          url="${{ needs.EC2-Deploy.outputs.instance_public_url }}"
          domain=$(echo $url | sed 's|http://||')
          echo "Domain: $domain"
          
          ip_address=$(dig +short $domain | grep -E '^[0-9.]+$' | head -n 1)
          echo "ip_address=$ip_address" >> $GITHUB_OUTPUT
          
          echo "Successfully found the public IP address of $domain: $ip_address"